export default {
  BitcoinFileReaderBlockCannotReadDirectory: 'bitcoin_file_reader_block_cannot_read_directory',
  BitcoinFileReaderBlockCannotReadFile: 'bitcoin_file_reader_block_cannot_read_file',
  BitcoinWalletIncorrectImportString: 'bitcoin_wallet_incorrect_import_string',
  BitcoinProcessorCannotProcessBlocksBeforeGenesis: 'bitcoin_processor_cannot_process_blocks_before_genesis',
  BitcoinProcessInvalidPreviousBlockHash: 'bitcoin_processor_invalid_previous_block_hash',
  BitcoinRawDataParserInvalidBlockData: 'bitcoin_raw_data_parser_invalid_block_data',
  BitcoinRawDataParserInvalidMagicBytes: 'bitcoin_raw_data_parser_invalid_magic_bytes',
  LockIdentifierIncorrectFormat: 'lock_identifier_incorrect_format',
  LockMonitorCurrentValueTimeLockInPendingState: 'lock_monitor_current_value_time_lock_in_pending_state',
  LockMonitorDesiredLockAmountIsNotWholeNumber: 'lock_monitor_desired_lock_amount_is_not_whole_number',
  LockMonitorNotEnoughBalanceForFirstLock: 'lock_monitor_not_enough_balance_for_first_lock',
  LockMonitorNotEnoughBalanceForRelock: 'lock_monitor_not_enough_balance_for_relock',
  LockMonitorTransactionFeesAmountIsNotWholeNumber: 'lock_monitor_transaction_fees_amount_is_not_whole_number',
  LockResolverDurationIsInvalid: 'lock_resolver_duration_is_invalid',
  LockResolverRedeemScriptIsInvalid: 'lock_resolver_redeem_script_is_invalid',
  LockResolverRedeemScriptIsNotLock: 'lock_resolver_redeem_script_is_not_lock',
  LockResolverTransactionIsNotPayingToScript: 'lock_resolver_transaction_is_not_paying_to_script',
  LockResolverTransactionNotConfirmed: 'lock_resolver_transaction_not_confirmed',
  LockResolverTransactionNotFound: 'lock_resolver_transaction_not_found',
  ValueTimeLockInPendingState: 'value_time_lock_in_pending_state',
  VersionManagerVersionStringNotFound: 'version_manager_version_string_not_found'
};
