export default {
  BitcoinWalletIncorrectImportString: 'bitcoin_wallet_incorrect_import_string',
  BitcoinProcessorBitcoinClientCurrentHeightNotUpToDate: 'bitcion_processor_bitcoin_client_current_height_not_up_to_date',
  BitcoinProcessorCannotProcessBlocksBeforeGenesis: 'bitcoin_processor_cannot_process_blocks_before_genesis',
  BitcoinProcessInvalidPreviousBlockHash: 'bitcoin_processor_invalid_previous_block_hash',
  BitcoinRawDataParserInvalidBlockData: 'bitcoin_raw_data_parser_invalid_block_data',
  BitcoinRawDataParserInvalidMagicBytes: 'bitcoin_raw_data_parser_invalid_magic_bytes',
  LockIdentifierIncorrectFormat: 'lock_identifier_incorrect_format',
  LockMonitorCurrentValueTimeLockInPendingState: 'lock_monitor_current_value_time_lock_in_pending_state',
  LockMonitorDesiredLockAmountIsNotWholeNumber: 'lock_monitor_desired_lock_amount_is_not_whole_number',
  LockMonitorNotEnoughBalanceForFirstLock: 'lock_monitor_not_enough_balance_for_first_lock',
  LockMonitorNotEnoughBalanceForRelock: 'lock_monitor_not_enough_balance_for_relock',
  LockMonitorTransactionFeesAmountIsNotWholeNumber: 'lock_monitor_transaction_fees_amount_is_not_whole_number',
  LockResolverDurationIsInvalid: 'lock_resolver_duration_is_invalid',
  LockResolverNormalizedFeeCannotBeCalculated: 'lock_resolver_normalized_fee_cannot_be_calculated',
  LockResolverRedeemScriptIsInvalid: 'lock_resolver_redeem_script_is_invalid',
  LockResolverRedeemScriptIsNotLock: 'lock_resolver_redeem_script_is_not_lock',
  LockResolverTransactionIsNotPayingToScript: 'lock_resolver_transaction_is_not_paying_to_script',
  LockResolverTransactionNotConfirmed: 'lock_resolver_transation_not_confirmed',
  LockResolverTransactionNotFound: 'lock_resolver_transaction_not_found',
  QuantileCalculatorGroupIdsNotSequential: 'quantile_calculator_group_ids_not_sequential',
  QuantileCalculatorInvalidQuantileMeasure: 'quantile_calculator_invalid_quantile_measure',
  ValueTimeLockInPendingState: 'value_time_lock_in_pending_state'
};
