name: Build and Test

on: [pull_request]

jobs:
  any-pr:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run build
    - run: npm run test:only # so we don't run the code coverage badge creation script and let the line below handle it
    - run: npm run badge:cc:ci # throws if README output differs to README to be checked in (thus detects if tests are not run)
