name: Release

on:
  push:
    branches:
      - master

jobs:
  push-master:
    # Only run on any commit that features the release commit message syntax in the commit message
    if: "contains(github.event.head_commit.message, 'chore(ref-imp): publish release')"
    name: Build, test and publish stable release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.15.3]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run test
    - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc 2> /dev/null
      env:
        NPM_TOKEN: ${{ secrets.NPMJS_TOKEN }}
    - run: git config user.name "DIF CI"
    - run: git config user.email "ci@identity.foundation"
    # Note - this is not required but it gives a clean failure prior to attempting a release if the GH workflow runner is not authenticated with npm.js
    - run: npm whoami
    - run: npm run publish:release
